// Build the single, self-contained `codethrough` binary with the frontend baked
// in. One script, three steps:
//   1. Vite production-builds the frontend into dist/ (hashed JS/CSS + worker +
//      wasm). Vite is required: the frontend uses SolidJS + UnoCSS + Pierre's
//      worker/wasm, which depend on Vite plugins Bun's bundler does not run.
//   2. Generate dist/binary_entry.ts: it imports every built asset
//      `with { type: "file" }` (how Bun bakes a file into a --compile binary),
//      installs the request-path -> baked-path manifest, then runs the CLI.
//   3. `bun build --compile` bakes the runtime + every imported asset into one
//      native executable.
//
// Output path overrides via `--outfile <path>` or CODETHROUGH_BINARY_OUTFILE;
// an explicit Bun target via `--target <bun-target>` or CODETHROUGH_BINARY_TARGET
// (native otherwise). Run as `bun run scripts/build.ts` (turbo `build:binary`).

import { readdir } from "node:fs/promises";
import { join, relative } from "node:path";
import { build as viteBuild } from "vite";

// The apps/cli root (this script lives in apps/cli/scripts).
const CLI_ROOT = join(import.meta.dir, "..");
const DIST_DIR = join(CLI_ROOT, "dist");
const ENTRY_FILE = join(DIST_DIR, "binary_entry.ts");
const VITE_CONFIG = join(CLI_ROOT, "vite.config.ts");
const DEFAULT_OUTFILE = "dist/codethrough";

// Where to write the binary, and which Bun target to compile for (empty =
// native). CLI flags win over the env defaults.
interface BuildOptions {
  outfile: string;
  target: string;
}

// Parse the optional flags over the env defaults. Unknown flags are an error so a
// typo never silently builds the wrong thing.
const parseOptions = (argv: readonly string[]): BuildOptions => {
  const options: BuildOptions = {
    outfile: Bun.env["CODETHROUGH_BINARY_OUTFILE"] ?? DEFAULT_OUTFILE,
    target: Bun.env["CODETHROUGH_BINARY_TARGET"] ?? "",
  };
  for (let i = 0; i < argv.length; i += 2) {
    const flag = argv[i];
    const value = argv[i + 1];
    if (value === undefined) {
      throw new Error(`Missing value for ${flag}`);
    }
    if (flag === "--outfile") {
      options.outfile = value;
    } else if (flag === "--target") {
      options.target = value;
    } else {
      throw new Error(`Unknown argument: ${flag}`);
    }
  }
  return options;
};

// Step 1: production-build the frontend. Run from CLI_ROOT so UnoCSS finds
// uno.config.ts (its plugin resolves the config from the cwd); the Vite config
// supplies the frontend root and dist/ output.
const buildFrontend = async (): Promise<void> => {
  process.chdir(CLI_ROOT);
  await viteBuild({ configFile: VITE_CONFIG });
};

// The Vite outputs to bake in: the SPA entry plus everything under assets/.
// Restricting to these keeps a stale prior binary or this generated entry out of
// the new binary, whatever the configured output path.
const isFrontendAsset = (rel: string): boolean => rel === "index.html" || rel.startsWith("assets/");

// Collect the frontend assets under dist/ as dist-relative, forward-slash paths
// (the request-path + import-specifier form), sorted for a stable entry. Derived
// from the actual tree so a new Vite chunk can never be missed.
const collectAssets = async (): Promise<string[]> => {
  const entries = await readdir(DIST_DIR, { recursive: true, withFileTypes: true });
  const assets = entries
    .filter((entry) => entry.isFile())
    .map((entry) => relative(DIST_DIR, join(entry.parentPath, entry.name)).split("\\").join("/"))
    .filter((rel) => isFrontendAsset(rel));
  return assets.toSorted();
};

// Render the generated entry: one import per asset, the manifest map, the install
// call, then the CLI. Identifiers are positional (a0, a1, ...) so no asset name
// can collide with a JS keyword or another asset.
const renderEntry = (assets: readonly string[]): string => {
  const imports = assets.map((rel, i) => `import a${i} from "./${rel}" with { type: "file" };`);
  const entries = assets.map((rel, i) => `  ${JSON.stringify(rel)}: a${i},`);
  return [
    "// AUTO-GENERATED by scripts/build.ts. DO NOT EDIT.",
    "// The compiled-binary entry: bakes in the built frontend and serves it from",
    "// the binary, then runs the CLI. Regenerated from dist/ on every build.",
    "",
    'import { setEmbeddedManifest } from "../src/server/embedded_registry.ts";',
    "",
    ...imports,
    "",
    "setEmbeddedManifest({",
    ...entries,
    "});",
    "",
    "// Run the CLI after the manifest is installed, so the first request already",
    "// resolves assets from the baked-in store.",
    'await import("../src/main.ts");',
    "",
  ].join("\n");
};

// Step 2: write dist/binary_entry.ts from the built dist/ tree.
const generateEntry = async (): Promise<void> => {
  const assets = await collectAssets();
  if (assets.length === 0) {
    throw new Error(`No frontend assets under ${DIST_DIR}; the Vite build produced nothing.`);
  }
  await Bun.write(ENTRY_FILE, renderEntry(assets));
  process.stdout.write(`Generated ${ENTRY_FILE} baking in ${assets.length} assets.\n`);
};

// Step 3: compile the binary. --compile bakes the runtime + every imported asset
// into one executable. The two size flags shrink it: --minify trims our bundled
// JS, --sourcemap=none keeps any source map out (the default, set so a future
// default change cannot bloat it). --target builds for a specific OS/arch when
// set; native otherwise.
const compileBinary = async (options: BuildOptions): Promise<void> => {
  const args = [
    "build",
    ENTRY_FILE,
    "--compile",
    "--minify",
    "--sourcemap=none",
    "--outfile",
    options.outfile,
  ];
  if (options.target !== "") {
    args.push("--target", options.target);
  }
  const proc = Bun.spawn(["bun", ...args], {
    cwd: CLI_ROOT,
    stdout: "inherit",
    stderr: "inherit",
  });
  const code = await proc.exited;
  if (code !== 0) {
    throw new Error(`bun build --compile failed with exit code ${code}`);
  }
};

const main = async (): Promise<void> => {
  const options = parseOptions(Bun.argv.slice(2));
  process.stdout.write("==> Building the frontend (vite)\n");
  await buildFrontend();
  process.stdout.write("==> Generating the embed entry from dist/\n");
  await generateEntry();
  process.stdout.write(`==> Compiling the binary -> ${options.outfile}\n`);
  await compileBinary(options);
  process.stdout.write(`==> Built ${options.outfile}\n`);
};

await main();
